# Generated by Django 3.1.5 on 2021-01-31 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField(null=True)),
                ('rated', models.CharField(max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(max_length=10)),
                ('popularity', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('region', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.moviecategory')),
            ],
        ),
        migrations.CreateModel(
            name='WatchedMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movie.listtype')),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movie.movies')),
            ],
            options={
                'unique_together': {('movie', 'code_name')},
            },
        ),
    ]
