# Generated by Django 3.1.5 on 2021-01-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='Id',
            new_name='id',
        ),
    ]
